"""Create outputs_addresses

Revision ID: 10c259903530
Revises: 33bd61598288
Create Date: 2015-01-13 12:35:00.105600

"""

# revision identifiers, used by Alembic.
revision = '10c259903530'
down_revision = '33bd61598288'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outputs_addresses',
    sa.Column('output_id', mysql.BIGINT, nullable=True),
    sa.Column('address_id', mysql.BIGINT, nullable=True),
    sa.Column('count', mysql.INTEGER, nullable=True),
    sa.PrimaryKeyConstraint('output_id', 'address_id', 'count')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outputs_addresses')
    ### end Alembic commands ###
