"""Add TransactionAddressInfoUpdate table

Revision ID: 14149dc0102f
Revises: 43c21abdde11
Create Date: 2014-07-08 22:51:00.465795

"""

# revision identifiers, used by Alembic.
revision = '14149dc0102f'
down_revision = '43c21abdde11'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_address_info_update',
    sa.Column('block_height', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('block_height')
    )
    op.create_index(op.f('ix_transaction_address_info_update_block_height'), 'transaction_address_info_update', ['block_height'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_address_info_update_block_height'), table_name='transaction_address_info_update')
    op.drop_table('transaction_address_info_update')
    ### end Alembic commands ###
