"""Add block_height in transaction

Revision ID: 1b3e01f7ddf0
Revises: 5aa35f8c9653
Create Date: 2014-06-29 12:52:15.372462

"""

# revision identifiers, used by Alembic.
revision = '1b3e01f7ddf0'
down_revision = '5aa35f8c9653'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('block_height', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transaction_block_height'), 'transaction', ['block_height'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_block_height'), table_name='transaction')
    op.drop_column('transaction', 'block_height')
    ### end Alembic commands ###
