"""Add received_at in transaction_info and value in transaction

Revision ID: 20f2dd43fa62
Revises: d6c05b083a7
Create Date: 2014-06-20 20:49:35.337496

"""

# revision identifiers, used by Alembic.
revision = '20f2dd43fa62'
down_revision = 'd6c05b083a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('value', sa.Numeric(precision=15, scale=8), nullable=True))
    op.create_index(op.f('ix_transaction_value'), 'transaction', ['value'], unique=False)
    op.add_column('transaction_info', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_transaction_info_received_at'), 'transaction_info', ['received_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_info_received_at'), table_name='transaction_info')
    op.drop_column('transaction_info', 'received_at')
    op.drop_index(op.f('ix_transaction_value'), table_name='transaction')
    op.drop_column('transaction', 'value')
    ### end Alembic commands ###
