"""Add pushed_from to all

Revision ID: 239117694fb3
Revises: 4455210b7c7
Create Date: 2014-12-10 16:22:00.510803

"""

# revision identifiers, used by Alembic.
revision = '239117694fb3'
down_revision = '4455210b7c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_block_pushed_from'), 'block', ['pushed_from'], unique=False)
    op.add_column('blocks', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_blocks_pushed_from'), 'blocks', ['pushed_from'], unique=False)
    op.add_column('inputs', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_inputs_pushed_from'), 'inputs', ['pushed_from'], unique=False)
    op.add_column('node', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_node_pushed_from'), 'node', ['pushed_from'], unique=False)
    op.add_column('node_activity', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_node_activity_pushed_from'), 'node_activity', ['pushed_from'], unique=False)
    op.add_column('outputs', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_outputs_pushed_from'), 'outputs', ['pushed_from'], unique=False)
    op.add_column('transaction', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transaction_pushed_from'), 'transaction', ['pushed_from'], unique=False)
    op.add_column('transaction_address_info', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transaction_address_info_pushed_from'), 'transaction_address_info', ['pushed_from'], unique=False)
    op.add_column('transaction_address_info_update', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transaction_address_info_update_pushed_from'), 'transaction_address_info_update', ['pushed_from'], unique=False)
    op.add_column('transaction_info', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transaction_info_pushed_from'), 'transaction_info', ['pushed_from'], unique=False)
    op.add_column('transaction_vin', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transaction_vin_pushed_from'), 'transaction_vin', ['pushed_from'], unique=False)
    op.add_column('transaction_vout', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transaction_vout_pushed_from'), 'transaction_vout', ['pushed_from'], unique=False)
    op.add_column('transactions', sa.Column('pushed_from', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_transactions_pushed_from'), 'transactions', ['pushed_from'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_pushed_from'), table_name='transactions')
    op.drop_column('transactions', 'pushed_from')
    op.drop_index(op.f('ix_transaction_vout_pushed_from'), table_name='transaction_vout')
    op.drop_column('transaction_vout', 'pushed_from')
    op.drop_index(op.f('ix_transaction_vin_pushed_from'), table_name='transaction_vin')
    op.drop_column('transaction_vin', 'pushed_from')
    op.drop_index(op.f('ix_transaction_info_pushed_from'), table_name='transaction_info')
    op.drop_column('transaction_info', 'pushed_from')
    op.drop_index(op.f('ix_transaction_address_info_update_pushed_from'), table_name='transaction_address_info_update')
    op.drop_column('transaction_address_info_update', 'pushed_from')
    op.drop_index(op.f('ix_transaction_address_info_pushed_from'), table_name='transaction_address_info')
    op.drop_column('transaction_address_info', 'pushed_from')
    op.drop_index(op.f('ix_transaction_pushed_from'), table_name='transaction')
    op.drop_column('transaction', 'pushed_from')
    op.drop_index(op.f('ix_outputs_pushed_from'), table_name='outputs')
    op.drop_column('outputs', 'pushed_from')
    op.drop_index(op.f('ix_node_activity_pushed_from'), table_name='node_activity')
    op.drop_column('node_activity', 'pushed_from')
    op.drop_index(op.f('ix_node_pushed_from'), table_name='node')
    op.drop_column('node', 'pushed_from')
    op.drop_index(op.f('ix_inputs_pushed_from'), table_name='inputs')
    op.drop_column('inputs', 'pushed_from')
    op.drop_index(op.f('ix_blocks_pushed_from'), table_name='blocks')
    op.drop_column('blocks', 'pushed_from')
    op.drop_index(op.f('ix_block_pushed_from'), table_name='block')
    op.drop_column('block', 'pushed_from')
    ### end Alembic commands ###
