"""Remove transaction type

Revision ID: 274183f65b9b
Revises: 29018199faab
Create Date: 2014-07-02 11:03:10.779238

"""

# revision identifiers, used by Alembic.
revision = '274183f65b9b'
down_revision = '29018199faab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('ix_transaction_type', table_name='transaction')
    op.drop_column('transaction', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('type', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=250), nullable=True))
    #op.create_index('ix_transaction_type', 'transaction', ['type'], unique=False)
    ### end Alembic commands ###
