"""Add TransactionSpending input_txid/vout index

Revision ID: 2b4163692c62
Revises: 352aa49de335
Create Date: 2014-07-08 17:19:20.813744

"""

# revision identifiers, used by Alembic.
revision = '2b4163692c62'
down_revision = '352aa49de335'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transaction_spending_input_txid_and_vout_index', 'transaction_spending', ['input_txid', 'vout_index'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_spending_input_txid_and_vout_index', table_name='transaction_spending')
    ### end Alembic commands ###
