"""Update node_activity table column ip_address to address

Revision ID: 311088515769
Revises: 59478b2503b4
Create Date: 2014-06-16 22:33:49.933816

"""

# revision identifiers, used by Alembic.
revision = '311088515769'
down_revision = '59478b2503b4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_activity', sa.Column('address', sa.String(length=250), nullable=True))
    op.drop_column('node_activity', 'ip_address')
    op.create_index(op.f('ix_node_activity_address'), 'node_activity', ['address'], unique=False)
    op.drop_index('ix_node_activity_ip_address', table_name='node_activity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_node_activity_ip_address', 'node_activity', ['ip_address'], unique=False)
    op.drop_index(op.f('ix_node_activity_address'), table_name='node_activity')
    op.add_column('node_activity', sa.Column('ip_address', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=250), nullable=True))
    op.drop_column('node_activity', 'address')
    ### end Alembic commands ###
