"""Create addresses

Revision ID: 33bd61598288
Revises: 41ea896ee6dc
Create Date: 2015-01-12 16:36:18.934729

"""

# revision identifiers, used by Alembic.
revision = '33bd61598288'
down_revision = '41ea896ee6dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', mysql.BIGINT, nullable=False),
    sa.Column('address', mysql.CHAR(36), nullable=True),
    sa.Column('first_time', mysql.BIGINT, nullable=True),
    sa.Column('last_time', mysql.BIGINT, nullable=True),
    sa.Column('num_txns', mysql.BIGINT, nullable=True),
    sa.Column('total_received', mysql.BIGINT, nullable=True),
    sa.Column('final_balance', mysql.BIGINT, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    ### end Alembic commands ###
