"""Add script_sig to inputs

Revision ID: 4455210b7c7
Revises: 36f1c282e0a2
Create Date: 2014-12-10 16:03:01.616416

"""

# revision identifiers, used by Alembic.
revision = '4455210b7c7'
down_revision = '36f1c282e0a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('script_sig', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputs', 'script_sig')
    ### end Alembic commands ###
