"""Create node table

Revision ID: 45a6ecf373be
Revises: None
Create Date: 2014-06-11 17:51:49.173356

"""

# revision identifiers, used by Alembic.
revision = '45a6ecf373be'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('ip_address', sa.String(length=250), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('start_height', sa.BigInteger(), nullable=True),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('hostname', sa.String(length=250), nullable=True),
    sa.Column('time_zone', sa.String(length=250), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=250), nullable=True),
    sa.Column('org', sa.String(length=250), nullable=True),
    sa.Column('asn', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_index(op.f('ix_node_asn'), 'node', ['asn'], unique=False)
    op.create_index(op.f('ix_node_city'), 'node', ['city'], unique=False)
    op.create_index(op.f('ix_node_country'), 'node', ['country'], unique=False)
    op.create_index(op.f('ix_node_hostname'), 'node', ['hostname'], unique=False)
    op.create_index(op.f('ix_node_latitude'), 'node', ['latitude'], unique=False)
    op.create_index(op.f('ix_node_longitude'), 'node', ['longitude'], unique=False)
    op.create_index(op.f('ix_node_org'), 'node', ['org'], unique=False)
    op.create_index(op.f('ix_node_start_height'), 'node', ['start_height'], unique=False)
    op.create_index(op.f('ix_node_time_zone'), 'node', ['time_zone'], unique=False)
    op.create_index(op.f('ix_node_timestamp'), 'node', ['timestamp'], unique=False)
    op.create_index(op.f('ix_node_user_agent'), 'node', ['user_agent'], unique=False)
    op.create_index(op.f('ix_node_version'), 'node', ['version'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_version'), table_name='node')
    op.drop_index(op.f('ix_node_user_agent'), table_name='node')
    op.drop_index(op.f('ix_node_timestamp'), table_name='node')
    op.drop_index(op.f('ix_node_time_zone'), table_name='node')
    op.drop_index(op.f('ix_node_start_height'), table_name='node')
    op.drop_index(op.f('ix_node_org'), table_name='node')
    op.drop_index(op.f('ix_node_longitude'), table_name='node')
    op.drop_index(op.f('ix_node_latitude'), table_name='node')
    op.drop_index(op.f('ix_node_hostname'), table_name='node')
    op.drop_index(op.f('ix_node_country'), table_name='node')
    op.drop_index(op.f('ix_node_city'), table_name='node')
    op.drop_index(op.f('ix_node_asn'), table_name='node')
    op.drop_table('node')
    ### end Alembic commands ###
