"""Update transactions

Revision ID: 4df830a960b2
Revises: afef8c5dcf1
Create Date: 2015-01-08 18:35:41.940025

"""

# revision identifiers, used by Alembic.
revision = '4df830a960b2'
down_revision = 'bbe8a259072'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('block_id', sa.BigInteger(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('is_coinbase', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True, index=True),
    sa.Column('blockID', sa.BigInteger(), nullable=True, index=True),
    sa.Column('is_coinbase', sa.Boolean(), nullable=True, index=True),
    sa.Column('pushed_from', sa.String(length=25), nullable=True, index=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
