"""Add node_activity table

Revision ID: 4e2a0ad36ba1
Revises: 45a6ecf373be
Create Date: 2014-06-16 17:13:35.241970

"""

# revision identifiers, used by Alembic.
revision = '4e2a0ad36ba1'
down_revision = '45a6ecf373be'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_activity_created_at'), 'node_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_node_activity_ip_address'), 'node_activity', ['ip_address'], unique=False)
    op.create_index(op.f('ix_node_activity_status'), 'node_activity', ['status'], unique=False)
    #op.drop_table('schema_migrations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('schema_migrations',
    #sa.Column('version', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=255), nullable=False),
    #mysql_collate=u'utf8_unicode_ci',
    #mysql_default_charset=u'utf8',
    #mysql_engine=u'InnoDB'
    #)
    op.drop_index(op.f('ix_node_activity_status'), table_name='node_activity')
    op.drop_index(op.f('ix_node_activity_ip_address'), table_name='node_activity')
    op.drop_index(op.f('ix_node_activity_created_at'), table_name='node_activity')
    op.drop_table('node_activity')
    ### end Alembic commands ###
