"""Add address_tag table

Revision ID: 4e98b1435763
Revises: 4e05d0e982d4
Create Date: 2014-07-30 14:16:37.999546

"""

# revision identifiers, used by Alembic.
revision = '4e98b1435763'
down_revision = '4e05d0e982d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('source', sa.String(length=250), nullable=True),
    sa.Column('link', sa.String(length=250), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_tag_address'), 'address_tag', ['address'], unique=False)
    op.create_index(op.f('ix_address_tag_source'), 'address_tag', ['source'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_tag_source'), table_name='address_tag')
    op.drop_index(op.f('ix_address_tag_address'), table_name='address_tag')
    op.drop_table('address_tag')
    ### end Alembic commands ###
