"""Create node table

Revision ID: 508531332e13
Revises: None
Create Date: 2014-06-09 16:26:56.242997

"""

# revision identifiers, used by Alembic.
revision = '508531332e13'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=250), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_ip_address'), 'node', ['ip_address'], unique=False)
    op.create_index(op.f('ix_node_timestamp'), 'node', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_timestamp'), table_name='node')
    op.drop_index(op.f('ix_node_ip_address'), table_name='node')
    op.drop_table('node')
    ### end Alembic commands ###
