"""Use ip_address+port as primary key in node table

Revision ID: 59478b2503b4
Revises: 4e2a0ad36ba1
Create Date: 2014-06-16 18:48:29.819164

"""

# revision identifiers, used by Alembic.
revision = '59478b2503b4'
down_revision = '4e2a0ad36ba1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('node', sa.Column('address', sa.String(length=250), nullable=False))
    #op.create_index(op.f('ix_node_ip_address'), 'node', ['ip_address'], unique=False)
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_node_ip_address'), table_name='node')
    #op.drop_column('node', 'address')
    ### end Alembic commands ###
