"""Add type in transaction model

Revision ID: 5aa35f8c9653
Revises: 20f2dd43fa62
Create Date: 2014-06-28 11:57:21.431890

"""

# revision identifiers, used by Alembic.
revision = '5aa35f8c9653'
down_revision = '20f2dd43fa62'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('type', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_transaction_type'), 'transaction', ['type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_type'), table_name='transaction')
    op.drop_column('transaction', 'type')
    ### end Alembic commands ###
